// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlxczwrgmxatdookuduz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFseGN6d3JnbXhhdGRvb2t1ZHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzEzNzAsImV4cCI6MjA2MjA0NzM3MH0.NQmmq8Z1c77-TqIyuqX0gtOJen7d6jccct_PEJU6ROg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);